; PlatformIO 工程 — ESP32 NFC 卡复制器
; 板子: XX5R69 = 经典 ESP32 (ESP-WROOM-32) => board = esp32dev
; 构建:  pio run
; 烧录:  pio run -t upload
; 串口:  pio device monitor   (115200)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600
; 若自动识别不到端口, 取消注释并按实际改:
; upload_port = /dev/ttyUSB0
; monitor_port = /dev/ttyUSB0

lib_deps =
    miguelbalboa/MFRC522@^1.4.11
    olikraus/U8g2@^2.35.19

build_flags =
    -DCORE_DEBUG_LEVEL=0
